// Mock auction lot data. 18 lots covering all the variation we need:
// - both days, varied conditions, some is_bat true with bat_buckets, some without images,
//   some with long titles, some with sparse/empty descriptions.

const LOTS = [
  {
    day: 'Sunday', lot_number: '0142',
    title: 'Vintage Henckels Twin Pro 8" chef knife with original walnut handle, lightly used',
    description: 'Forged carbon steel, made in Solingen, Germany. Edge has been honed but never reground. Small patina spots near bolster, otherwise excellent. Comes with original cardboard sleeve.',
    condition: 'Like New',
    thumb_url: 'https://picsum.photos/seed/lot1/600/450',
    image_url: 'https://picsum.photos/seed/lot1/1200/900',
    lot_url: 'https://example.com/lot/0142',
    category: 'Kitchen', subcategory: 'Knives & Cutlery',
    is_bat: true, bat_buckets: ['Kitchen', 'Knives'],
  },
  {
    day: 'Sunday', lot_number: '0188',
    title: 'Anker PowerCore 26800mAh portable battery, 3-port',
    description: 'As shown.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot2/600/450',
    image_url: 'https://picsum.photos/seed/lot2/1200/900',
    lot_url: 'https://example.com/lot/0188',
    category: 'Electronics', subcategory: 'Power & Charging',
    is_bat: true, bat_buckets: ['Batteries', 'Travel'],
  },
  {
    day: 'Sunday', lot_number: '0204',
    title: 'Box of assorted Phillips and flathead screwdrivers',
    description: '',
    condition: 'Heavily Used',
    thumb_url: '', // broken — test fallback
    image_url: '',
    lot_url: 'https://example.com/lot/0204',
    category: 'Tools', subcategory: 'Hand Tools',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Sunday', lot_number: '0231',
    title: 'Le Creuset 5.5qt round Dutch oven, marseille blue',
    description: 'Enameled cast iron. Interior shows light utensil marks consistent with normal use. Exterior enamel is bright with no chips. Lid knob is original phenolic. A real workhorse.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot4/600/450',
    image_url: 'https://picsum.photos/seed/lot4/1200/900',
    lot_url: 'https://example.com/lot/0231',
    category: 'Kitchen', subcategory: 'Cookware',
    is_bat: true, bat_buckets: ['Kitchen'],
  },
  {
    day: 'Sunday', lot_number: '0277',
    title: 'Philips Hue starter kit, four A19 white & color bulbs with bridge',
    description: 'Original box, all components present. Bridge has been factory reset. Bulbs test working with current Hue app.',
    condition: 'Like New',
    thumb_url: 'https://picsum.photos/seed/lot5/600/450',
    image_url: 'https://picsum.photos/seed/lot5/1200/900',
    lot_url: 'https://example.com/lot/0277',
    category: 'Electronics', subcategory: 'Smart Home',
    is_bat: true, bat_buckets: ['Smart Home', 'Lighting'],
  },
  {
    day: 'Sunday', lot_number: '0301',
    title: 'Pair of mid-century walnut nightstands',
    description: 'Two-drawer, tapered legs, original brass pulls. Minor surface scratches on tops, no veneer lifting, all drawers slide smoothly. Sold as a pair.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot6/600/450',
    image_url: 'https://picsum.photos/seed/lot6/1200/900',
    lot_url: 'https://example.com/lot/0301',
    category: 'Furniture', subcategory: 'Bedroom',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Sunday', lot_number: '0344',
    title: 'Crate of National Geographic magazines, 1970s–1980s',
    description: 'Approximately 60 issues. Mixed condition; most very good with some spine wear.',
    condition: 'Fair',
    thumb_url: 'https://picsum.photos/seed/lot7/600/450',
    image_url: 'https://picsum.photos/seed/lot7/1200/900',
    lot_url: 'https://example.com/lot/0344',
    category: 'Books & Media', subcategory: 'Magazines',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Sunday', lot_number: '0389',
    title: 'Wooden cutting board (large)',
    description: '',
    condition: 'New',
    thumb_url: 'https://picsum.photos/seed/lot8/600/450',
    image_url: 'https://picsum.photos/seed/lot8/1200/900',
    lot_url: 'https://example.com/lot/0389',
    category: 'Kitchen', subcategory: 'Prep',
    is_bat: true, bat_buckets: ['Kitchen'],
  },
  {
    day: 'Sunday', lot_number: '0412',
    title: 'Schwinn Varsity 10-speed bicycle, 1972, original Campy components',
    description: 'Frame is straight, paint is original with patina. Tires hold air. Shifters work through full range. A project for the right person.',
    condition: 'Heavily Used',
    thumb_url: 'https://picsum.photos/seed/lot9/600/450',
    image_url: 'https://picsum.photos/seed/lot9/1200/900',
    lot_url: 'https://example.com/lot/0412',
    category: 'Sporting Goods', subcategory: 'Bicycles',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Monday', lot_number: '1028',
    title: 'Eero Pro 6 mesh wifi system, set of 3',
    description: 'All three units, all power adapters, original ethernet cable. Reset to factory defaults.',
    condition: 'Like New',
    thumb_url: 'https://picsum.photos/seed/lot10/600/450',
    image_url: 'https://picsum.photos/seed/lot10/1200/900',
    lot_url: 'https://example.com/lot/1028',
    category: 'Electronics', subcategory: 'Networking',
    is_bat: true, bat_buckets: ['Smart Home', 'Networking'],
  },
  {
    day: 'Monday', lot_number: '1077',
    title: 'Assorted Pyrex mixing bowls (set of 4, vintage)',
    description: 'As shown.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot11/600/450',
    image_url: 'https://picsum.photos/seed/lot11/1200/900',
    lot_url: 'https://example.com/lot/1077',
    category: 'Kitchen', subcategory: 'Bakeware',
    is_bat: true, bat_buckets: ['Kitchen'],
  },
  {
    day: 'Monday', lot_number: '1102',
    title: 'DeWalt 20V max cordless drill, two batteries, charger, hard case',
    description: 'Drill spins true, chuck holds tight. Both batteries hold charge through a full session. Case has scuffs but latches fine.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot12/600/450',
    image_url: 'https://picsum.photos/seed/lot12/1200/900',
    lot_url: 'https://example.com/lot/1102',
    category: 'Tools', subcategory: 'Power Tools',
    is_bat: true, bat_buckets: ['Batteries', 'Tools'],
  },
  {
    day: 'Monday', lot_number: '1156',
    title: 'Large lot of costume jewelry, brooches, earrings, necklaces',
    description: '',
    condition: 'Fair',
    thumb_url: '', // broken
    image_url: '',
    lot_url: 'https://example.com/lot/1156',
    category: 'Jewelry', subcategory: 'Costume',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Monday', lot_number: '1183',
    title: 'Apple HomePod mini (white)',
    description: 'Original box. Tested and pairs to current iOS.',
    condition: 'Like New',
    thumb_url: 'https://picsum.photos/seed/lot14/600/450',
    image_url: 'https://picsum.photos/seed/lot14/1200/900',
    lot_url: 'https://example.com/lot/1183',
    category: 'Electronics', subcategory: 'Smart Home',
    is_bat: true, bat_buckets: ['Smart Home'],
  },
  {
    day: 'Monday', lot_number: '1217',
    title: 'Cast iron skillet, unmarked, 10"',
    description: 'Well seasoned. No cracks or warps. Smooth cooking surface.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot15/600/450',
    image_url: 'https://picsum.photos/seed/lot15/1200/900',
    lot_url: 'https://example.com/lot/1217',
    category: 'Kitchen', subcategory: 'Cookware',
    is_bat: true, bat_buckets: ['Kitchen'],
  },
  {
    day: 'Monday', lot_number: '1244',
    title: 'Three boxes of assorted hardware: nails, screws, bolts, washers',
    description: 'As shown. Heavy.',
    condition: 'Good',
    thumb_url: 'https://picsum.photos/seed/lot16/600/450',
    image_url: 'https://picsum.photos/seed/lot16/1200/900',
    lot_url: 'https://example.com/lot/1244',
    category: 'Tools', subcategory: 'Hardware',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Monday', lot_number: '1289',
    title: 'Ridgeback merino wool throw blanket, charcoal, never used with original tag',
    description: 'New with tag. Folded, never washed.',
    condition: 'New',
    thumb_url: 'https://picsum.photos/seed/lot17/600/450',
    image_url: 'https://picsum.photos/seed/lot17/1200/900',
    lot_url: 'https://example.com/lot/1289',
    category: 'Home Goods', subcategory: 'Textiles',
    is_bat: false, bat_buckets: [],
  },
  {
    day: 'Monday', lot_number: '1322',
    title: 'Bose QuietComfort 35 II headphones, original case',
    description: 'Some wear on the ear cushion edges. Bluetooth pairs without issue. Active noise canceling works as expected.',
    condition: 'Fair',
    thumb_url: 'https://picsum.photos/seed/lot18/600/450',
    image_url: 'https://picsum.photos/seed/lot18/1200/900',
    lot_url: 'https://example.com/lot/1322',
    category: 'Electronics', subcategory: 'Audio',
    is_bat: true, bat_buckets: ['Audio'],
  },
];

window.LOTS = LOTS;
