#!/usr/bin/env python3
"""
Sweep the spent intermediates out of data/categorized once a run is deployed.

    python3 tools/tidy.py <ID>            # delete
    python3 tools/tidy.py <ID> --dry-run  # list only

A full run leaves ~35 files behind for the week and every mid-week delta adds
~20 more, so by d2 the folder is unreadable and the files the NEXT delta
actually needs are buried. Almost all of them are inputs to a ChatGPT chat or
the chat's raw reply, and once `expand_flags.py` / `recall_check.py apply` /
`expand_resale.py` have folded them into `_flags.json` and `_resale.json`
nothing reads them again (CLAUDE.md, "Data retention"). This removes exactly
those, for the parent ID and for every `<ID>_dN` delta, and keeps everything a
later step still reads:

kept
    `_categorized.json`, `_resale.json`      build inputs; delta merge folds onto them
    `_for_agent.json`                        verify's lot_set_sha; the seed backtest;
                                             merge's foreign-lot check on each delta
    `_base.json`, `_prefilter.json`          step 5's merge base (regenerated by merge)
    `_flags.json`                            EVERY delta's is re-folded on each merge;
                                             the parent's feeds `prefilter.py --audit`
    `_resale_deduped.json`                   retention: valuations stay true next week
    `_dN_resale.json`                        re-folded on each merge
    `README.md`, `auction_703264_categorized.json`  tracked; the latter is a test fixture

removed, per ID, only once its pass is provably folded in
    `_chunk_NN.json`, `_chunk_NN_flags.json`, `_chunk_NN_prompt.md`,
    `_flag_groups.json`                      once `_flags.json` exists
    `_recall.json`, `_recall_flags.json`, `_recall_prompt.md`,
    `_flags_before_recall.json`              once the recall was applied (or was
                                             never planned); a planned-but-unapplied
                                             recall is left alone
    `_for_resale.json`, `_resale_groups.json`, `_resale_prompt.md`
                                             once `_resale.json` exists
    `_candidates.json`, `_sweep.json`        prefilter diagnostics, rebuilt every run
    `context.yaml`                           rebuilt by every chunk_flagging run

`data/raw/auction_<ID>_dN.json` is NOT touched: `delta.py` numbers the next
delta from those files, and deleting d1's would make the next start write d1
again over the top of it. Step 0's sweep removes them with the week.

The recall guard is what makes this safe to run mid-pass: `apply` refuses a
second run by content (lots already carrying a bucket), not by the presence of
`_flags_before_recall.json`, so removing the backup cannot cause a double
apply. A planned recall whose reply has not been applied yet is detected by
`_recall.json` existing while `_flags_before_recall.json` does not.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

OUT_DIR = Path("data/categorized")

_CHUNK_RE = re.compile(r"_chunk_\d+(_flags\.json|_prompt\.md|\.json)$")


def delta_ids(aid: str, out_dir: Path = OUT_DIR) -> list[str]:
    """`<ID>_dN` for every delta that has left anything in the folder."""
    pat = re.compile(rf"^auction_{re.escape(aid)}_d(\d+)_")
    found = {int(m.group(1)) for p in out_dir.iterdir() if (m := pat.match(p.name))}
    return [f"{aid}_d{n}" for n in sorted(found)]


def spent_files(aid: str, out_dir: Path = OUT_DIR) -> tuple[list[Path], list[str]]:
    """Files safe to delete for one ID, plus notes on what was deliberately kept."""
    p = lambda suffix: out_dir / f"auction_{aid}{suffix}"  # noqa: E731
    doomed: list[Path] = []
    kept: list[str] = []

    flags_done = p("_flags.json").exists()
    chunk_files = sorted(f for f in out_dir.glob(f"auction_{aid}_chunk_*")
                         if _CHUNK_RE.search(f.name))
    if flags_done:
        doomed += chunk_files
        doomed.append(p("_flag_groups.json"))
    elif chunk_files:
        kept.append(f"{aid}: {len(chunk_files)} chunk file(s) — no _flags.json yet, "
                    f"the flagging pass is still open")

    recall_planned = p("_recall.json").exists()
    recall_applied = p("_flags_before_recall.json").exists()
    if recall_applied or not recall_planned:
        doomed += [p("_recall.json"), p("_recall_flags.json"), p("_recall_prompt.md"),
                   p("_flags_before_recall.json")]
    else:
        kept.append(f"{aid}: recall files — planned but `recall_check.py apply` "
                    f"has not run")

    if p("_resale.json").exists():
        doomed += [p("_for_resale.json"), p("_resale_groups.json"), p("_resale_prompt.md")]
    elif p("_for_resale.json").exists():
        kept.append(f"{aid}: resale inputs — no _resale.json yet, the resale pass is "
                    f"still open (or this is a flagging-only week: delete by hand)")

    doomed += [p("_candidates.json"), p("_sweep.json")]
    return [f for f in doomed if f.exists()], kept


def plan(aid: str, out_dir: Path = OUT_DIR) -> tuple[list[Path], list[str]]:
    doomed: list[Path] = []
    kept: list[str] = []
    for one in [aid, *delta_ids(aid, out_dir)]:
        d, k = spent_files(one, out_dir)
        doomed += d
        kept += k
    ctx = out_dir / "context.yaml"
    if ctx.exists():
        doomed.append(ctx)
    return doomed, kept


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("auction_id", help="the week's ID (`combined` on a two-auction week)")
    ap.add_argument("--dry-run", action="store_true", help="list, delete nothing")
    args = ap.parse_args(argv)

    if not (OUT_DIR / f"auction_{args.auction_id}_categorized.json").exists():
        sys.exit(f"Error: no auction_{args.auction_id}_categorized.json in {OUT_DIR} — "
                 f"tidy runs after a deployed week, and only under the week's ID.")

    doomed, kept = plan(args.auction_id)
    total = sum(f.stat().st_size for f in doomed)
    verb = "would remove" if args.dry_run else "removed"
    for f in doomed:
        if not args.dry_run:
            f.unlink()
        print(f"  {verb:12s} {f.name}")
    print(f"\n{len(doomed)} file(s), {total / 1024 / 1024:.1f} MB {verb}")
    for note in kept:
        print(f"  kept: {note}")

    gone = set(doomed)
    remaining = sorted(p.name for p in OUT_DIR.iterdir() if p.is_file() and p not in gone)
    print(f"\n{len(remaining)} file(s) left in {OUT_DIR}:")
    for name in remaining:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
